name: examples-python

on:
  push:
    paths:
      - "examples/python/**"
      - ".github/workflows/examples-python.yml"
  pull_request:
    paths:
      - "examples/python/**"

permissions:
  contents: read

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: "3.12"
      - name: Compile and test the server
        working-directory: examples/python/server
        run: |
          pip install -r requirements.txt
          python -m py_compile server.py test_server.py
          python -m unittest test_server.py
      - name: Compile the client
        working-directory: examples/python/client
        run: |
          pip install -r requirements.txt
          python -m py_compile client.py
